
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Volumes/TZPassport/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Darwin - 21.5.0 - x86_64
...
